### ISSUE TITLE
Changing dates doesn't update the screen

### ISSUE THREAD

**Issue by YalorMewn** [Giveth/xchange-rates#10]
When you change the dates for amounts and currency nothing happens. 

To replicate choose a figure: 
<img width="636" alt="screen shot 2018-05-27 at 5 27 42 pm" src="https://user-images.githubusercontent.com/34845103/40587755-cb404eae-61d3-11e8-8ae7-090bc8b9cc67.png">
 
Change the date: 
<img width="629" alt="screen shot 2018-05-27 at 5 27 23 pm" src="https://user-images.githubusercontent.com/34845103/40587759-d7a8a57e-61d3-11e8-8ea5-8ec583ee7e5d.png">

Nothing happens, 

But if you click the switcher back and forth it updates to the correct date: 
<img width="636" alt="screen shot 2018-05-27 at 5 27 42 pm copy" src="https://user-images.githubusercontent.com/34845103/40587764-e55d8e64-61d3-11e8-9469-d82f18cc58fd.png">

Maybe an enter button or something should added.

**Comment by dapplion** [comment]
This should not happen anymore. The algorithm watching changes is more robust
