### ISSUE TITLE
When you manually type dates into the date tab, you must include the day for it to work

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/xchange-rates#11]
I type Feb 1, 2018 and it goes to the last date interests the copy link... Also I could do a screen shot that would make it look like the screen shot was something it's not.

**Comment by dapplion** [comment]
I disabled the manual text editing. You can only change dates now by picking a date on the calendar. This way you:
- ensure that the rate corresponds to the displayed date
- avoid wrong dates due to typos
- future date that the user may type
